# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 🚀 Younessssssss The Coder
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Hello! 👋 I'm a developer who's had my share of ups and downs. 🎢 I've worked on cool projects,
  but sometimes, things didn't go as planned. 
  🙈 But hey, that's part of the journey, right? This blog is about turning those 'Oops' into 'Eureka' moments! 🎉 I'll share my lessons,tips, and the fun stuff I've learned along the way.
  So, let's navigate this coding adventure together! 😊"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://younessssssss.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: younessssssss
github_username: younessssssss

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  
google_analytics: G-11S3BWHXR7  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
